spring:
  cloud:
    gateway:
      routes:
        - id: query_route
          uri: https://baidu.com
          predicates:
            - Query=test,123
        - id: method_route
          uri: https://baidu.com
          predicates:
              - Method=GET,POST

    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

server:
  port: 88