spring:
  data:
    mongodb:
      host: 193.112.195.243
      database: test
      port: 27017
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
  cloud:
#    #服务的注册和发现
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
    #阿里云配置
    alicloud:
      access-key: LTAI4GC5r56UCqM8pfs3MPTK
      secret-key: aetrH5EM7oHv7KY81dNqamq9Kcyl9I
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com



#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8093
  servlet:
    context-path: /restful/api/v1/system