spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/human_resource?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: nzh
      password: 123456
  cloud:
    #服务的注册和发现
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        refresh-enabled: true
        server-addr: 127.0.0.1:8848
        namespace: 95303e2d-3b80-4f5e-b545-0451585c4313
        group: group1
  application:
    name: hrrecruit

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.hr.*.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
server:
  port: 8091